### ISSUE TITLE
Mercurius 1.0.3 is mandatory to connect to FTB Beyond 1.5.3 Servers

### ISSUE THREAD

**Issue by megalous** [MinecraftForge/Mercurius#3]
Hello,
you have removed the 1.0.3 version of Mercurius from Curse, so i can't download it.
Unfortunately it is mandatory to connect to any FTB Beyond 1.5.3 Servers, i have tried to connect with the Snooper setting off to no avail.
I do not know how the curse launcher deals with this, but the curseDownloader from portablejim can not fetch it anymore.
Is it really necessary for the server to require mercurius on the client.

**Comment by ironrainomega** [comment]
This isn't a Mercurius bug, but a CurseDownloader bug for portablejim as he's not handling archived versions correctly. The Twitch App can pull old versions of Mercurius when downgrading to older versions. The 1.0.3 files aren't deleted just archived.
