### ISSUE TITLE
Mercuris Updater 1.12 Error

### ISSUE THREAD

**Issue by trekinsanity** [MinecraftForge/Mercurius#6]
I just installed, the newest version of Forge for 1.12 (forge-1.12-14.21.0.2334-installer.jar). I get the following error: "mercuruis_updater ... requires Minecraft between 1.11 and 1.11.2 ...." I have deleted the "MercuriusUpdater-1.12.jar" file and tries again. A new MercuriusUpdater-1.12.jar was downloaded, however, I am getting the same results.

**Comment by ironrainomega** [comment]
Let me look into this.

**Comment by ironrainomega** [comment]
Should be fixed, remove the jar file and try again.
